### ISSUE TITLE
Possible issue with sprintf()

### ISSUE THREAD

**Issue by gesslar** [fluffos/fluffos#696] opened 2020-11-05 02:18 UTC
Migrating from MudOS to FluffOS and I noticed on one of my command displays that sprintf is behaving differently under FluffOS.

Below is sample code.

```C
int cmd_test()
{
    string *dummy, *spell_names, column, *formatted, result ;


    // Load up the left column with dummy info
    dummy  = ({ "one", "two", "three", "four", "five", "six" }) ;
    // Get some spell names
    spell_names = ({
        "A good spell", "This spell is ok", "Not a spell",
        "Fire fire fire", "Toad smooches", "Hello world"        
    }) ;
    // Setup the column that will separate in the middle
    column = repeat_string("|\n", 6);

    // Format the spell_names
    formatted = map( spell_names, "format_spell_entry", this_object() ) ;

    // Now put everything into columns
    result = sprintf(
        "\n%-=31s %-=2s %-=45s",

        implode(dummy, "\n"),
        column,
        implode(formatted, "\n")
    );

    // Print it out!
    write(result + "\n") ;

    return TRUE ;
}


string format_spell_entry(string spell_name )
{
    string bar;
    int points, diff, grace;

    points = 5 ;
    diff   = 10 - points ;

    bar  = repeat_string("@", points);
    bar += repeat_string("-", diff);

    return sprintf("(%s) %-25s", bar, spell_name);
}
```

And here are the results:
```
> test
one                             |  (@@@@@-----) A good spell            
two                             |  
three                           |  (@@@@@-----) This spell is ok        
four                            |  
five                            |  (@@@@@-----) Not a spell             
six                             |  
                                   (@@@@@-----) Fire fire fire          
                                   
                                   (@@@@@-----) Toad smooches           
                                   
                                   (@@@@@-----) Hello world   
```

However, if I change the return statement in `format_spell_entry` to  `return sprintf("(%s) %-'.'25s", bar, spell_name);`, I get the following (adding a period as a padding character):
```
> test
one                             |  (@@@@@-----) A good spell.............
two                             |  (@@@@@-----) This spell is ok.........
three                           |  (@@@@@-----) Not a spell..............
four                            |  (@@@@@-----) Fire fire fire...........
five                            |  (@@@@@-----) Toad smooches............
six                             |  (@@@@@-----) Hello world..............
```

If I run the exact same code (without the padding character) under MudOS v22, I get the following results:

```
> test

one                             |  (@@@@@-----) A good spell             
two                             |  (@@@@@-----) This spell is ok         
three                           |  (@@@@@-----) Not a spell              
four                            |  (@@@@@-----) Fire fire fire           
five                            |  (@@@@@-----) Toad smooches            
six                             |  (@@@@@-----) Hello world    
```

**Comment by dzpao** [comment] 2020-11-09 16:39
I've spent some time looking into the issue, and while I haven't definitively solved the problem, I've found an MWE that looks like a much easier explanation.

I'm posting it up now for your consideration.

Anyone interested can reproduce the problem on the master version by saving the following code as `fluffos/testsuite/command/test.c`.

```C
int cmd_test()
{
    string *col1, *col2_good, *col2_bad, result;

    col1        = ({ "one",     "two",      "three"     });
    col2_good   = ({ "line1",   "line2",    "line3"     });
    col2_bad    = ({ "line1 ",  "line2 ",   "line3 "    });

    result = sprintf(
        "\n%-=10s %-=20s",
        implode(col1, "\n"),
        implode(col2_good, "\n")
    );

    write( "------- looks like GOOD -------"
           + result
           + "\n--------------------------------\n");

    result = sprintf(
        "\n%-=10s %-=20s",
        implode(col1, "\n"),
        implode(col2_bad, "\n")
    );

    write("------- looks like BAD -------"
          + result
           + "\n--------------------------------\n");

    return 1;
}

int main(object me) {
    cmd_test();
}
```

The above code will produce the following output:
```
> update /command/test
> test
------- looks like GOOD -------
one        line1
two        line2
three      line3
--------------------------------
------- looks like BAD -------
one        line1
two
three      line2

           line3
--------------------------------
What?
>
```

**Comment by thefallentree** [comment] 2020-11-09 16:47
What does this mean? The space at the end of col was not properly ignored?

**Comment by dzpao** [comment] 2020-11-09 16:49
Yes, I've updated my code so it looks clearer.

**Comment by dzpao** [comment] 2020-11-09 16:52
It does seem that there are some bugs in the `sprintf` code, and intuitively `sprintf` shouldn't treat spaces and other visible characters differently here.

**Comment by dzpao** [comment] 2020-11-10 03:16
I've located the bug. I tried changing it myself and it looks fine, which is a good indication that my findings are correct. However, since `u8_truncate_below_width` is a more basic function than `sprintf`, I need to evaluate the effect of the changes.

https://github.com/fluffos/fluffos/blob/master/src/base/internal/strutils.cc#L479-L483

```C
    // Eat the last space
    if (break_length > 1 && src[break_length - 1] == ' ') {
      break_length--;
      break_width--;
    }
```

The good news is that `u8_truncate_below_width` has no other user than `sprintf.cc`, and the bad news is that it looks like the change can't be fixed in just a couple of lines of code.  It may be necessary to adjust the semantics of `u8_truncate_below_width`.

```cpp
// Truncate string to last valid codepoint that doesn't exceed maximum width, returns real width and
// new len. If brake_at_space, then attempts to truncate before the last ' ' character. If
// always_break_at_newline, then always truncate to first '\n' character. Invalid codepoints are
// replaced to 0xfffd;
void u8_truncate_below_width(const char *src, size_t len, size_t max_width, bool break_for_line,
                             bool always_break_before_newline, size_t *out_len, size_t *out_width) {
```

The documentation for the function mentions two options, one is `brake_at_space` and the other is `always_break_at_newline`, but it's not clear what the logic should be when both options are `true` at the same time. The reality is that `sprintf` calls provide exactly both options (both `true`) at the same time.

The test cases can also be complex, such as one space at the end, multiple spaces but not more than the width, multiple spaces but more than the width, a space in the middle of a word, a space at the end of a line, and a space at the beginning of a line.

I'll record my findings here, and then I'll stop here on my end.

@thefallentree Well, you can take another look and refer to my progress to see what should eventually be changed. But from the user side, it really should be considered a bug.

@gesslar Until the bug is fixed, we can circumvent the problem by trimming the blank at the end of the line. That way the `sprintf` table function will still work.

**Closed** 2021-03-02 03:38 UTC
Labels: bug
