### ISSUE TITLE
Efun request

### ISSUE THREAD

**Issue by zero9k** [fluffos/fluffos#385] opened 2017-09-21 03:03 UTC
- JSON
Could you please make save_object() and restore_object() support JSON? 
We also need efuns to save variable to or restore variable from JSON format file.
- sort_string
We use this simul_efun to make outputing descriptions or messages more conveniment.
```
string sort_string(string input, int width, int prefix)
{
        int i;
        int sl;
        int len;
        int esc;
        string result;

        result = "";

        len = prefix;
        esc = 0;
        sl = strlen(input);
        for (i = 0; i < sl; i++)
        {
                if (len >= width && input[i] != '\n')
                {
                        int k;
                        k = i;
                        if (input[i] == 27)
                                while (k < sl && input[k++] != 'm');

                        switch ((k < sl - 1) ? input[k..k+1] : 0)
                        {
                        case "：":
                        case "”":
                        case "。":
                        case "，":
                        case "；":
                        case "）":
                        case " )":
                        case "！":
                        case "？":
                        case "、":
                                if (k != i)
                                {
                                        result += input[i..k + 1];
                                        i = k + 1;
                                        continue;
                                }
                                break;
                        default:
                                len = 0;
                                result += "\n";
                                break;
                        }
                }

                if (input[i] == 27)
                        esc = 1;

                if (! esc)
                {
                        if (input[i] > 160)
                        {
                                result += input[i..i+1];
                                i ++;
                                len += 2;
                                continue;
                        }
                        if (input[i] == '\n')
                        {
                                result += "\n";
                                len = 0;
                                continue;
                        }
                }

                result += input[i..i];
                if (! esc) len++;

                if (esc && input[i] == 'm')
                        esc = 0;
        }

        if (i < sl)
                result += input[i..sl-1];

	if (len) result += "\n";

        return result;
}

```

**Comment by cartercheng** [comment] 2017-09-21 11:40
I am not sure how best to do this. It probably isn't too difficult to implement in principle using a C++/C JSON library. The issue is the API. Do we want an extra argument to save/restore object and save fetch variable to designate the saves in JSON format or have a config option that changes the standard functions to save in this format?

**Comment by thefallentree** [comment] 2017-09-21 13:16
a new save_object_json and restore_object_json seems to be more preferable.

**Comment by quixadhal** [comment] 2017-09-21 15:48
If you allow something to create objects from JSON strings, and likewise store objects as JSON strings, you will have more functionality than reading or writing directly to files.  It’s trivial to wrap those with sefuns that read or write the files, if you like.

The advantage of being able to work with strings though is that you can then create objects on the fly, using the virtual object system, and not care if they have physical file backing or not.  You could even store them in an object database, if you like.

Sent from Mail for Windows 10

**Comment by cartercheng** [comment] 2017-09-21 21:05
should this merge with #333?

**Comment by zero9k** [comment] 2017-09-25 01:49
Or just like @cartercheng said ... maybe... think bigger... - -! make fluffos support both LPC variables and JSON (JS) variables... We can declare variables in both ways ( "({ })" and "[ ]" for arrays, "([ ])" and "{ }" for mappings and etc. ). Then we can of course have both save_object restore_object and save_object_json and restore_object_json.

**Comment by cartercheng** [comment] 2017-09-25 14:26
I am not sure making such a change will not introduce ambiguities in the parsing. I think there might be a reason that lpc uses the uglier double char open and close. Hard to say though without testing.

**Comment by quixadhal** [comment] 2017-09-25 15:55
LPC uses doubled characters to simplify the parser.  Braces are used for scope, and to act as BEGIN and END markers for clauses, such as for loops, functions, etc.  Obviously, other languages deal with the ambiguity, but it would require you to rewrite the LPC grammar and parser to handle it.  Remember that LPC was written in the late 1980’s, when RAM was extremely limited and CPU power was likewise very tight.  The extra steps of resolving the ambiguity was either too hard for Lars to do at the time, or was deemed too expensive for the limited hardware, since things had to be (essentially) JIT compiled on the spot.

These days, it all boils down to compatibility and the time you want to spend.  There’s no real reason you can’t use [] for arrays and {} for mappings, along with the other uses.  There’s also no real reason you can’t use [] for both arrays and mappings, since a mapping can be treated as an array where the even elements are keys, and the odd elements are values (this is how perl does it, BTW).

The nasty part comes when trying to deal with anonymous functions (happy code).   In that context, it can be hard to tell if a pair of braces were meant to be containment (scope), or a mapping that holds lambda results.  Personally, I’d go with the [] being data and the {} being code… but no matter how you do it, you’re changing the language and making it not quite compatible.  How much that matters, I dunno.  I do know it’s a good amount of work and will probably require you to make multiple passes over the source to resolve the ambiguities.

Sent from Mail for Windows 10

**Comment by cartercheng** [comment] 2017-09-25 19:34
The reason I question why it is possible is that I tried something similar before in ANTLR v3 and it didn't work.

**Comment by cartercheng** [comment] 2017-09-25 19:36
And actually the parsing hasn't changed much in terms of technology since when lpc originated. I think we have been using the lex/yacc tandem for quite sometime now. I don't think the underlying technology has changed since many parsing systems still rely on LALR(1). So anything befuddling the parser generator back then still applies today.

**Comment by quixadhal** [comment] 2017-09-25 19:45
It’s not that.  The reason I pointed out the hardware difference is because this is an interpreted language.  In 1988, the interpreter had to keep up with running this at an acceptable speed on hardware where the CPU ran at 40MHz and you had 4MB of RAM to work with.  The tools don’t matter, the runtime did.  These days, the CPU running these games are several orders of magnitude faster, and you have crazy amounts of RAM to use, so a more complex parser that needs a few extra cycles isn’t a big deal.

Put another way, back in 1992, our DikuMUD (all hard coded C) had to be limited to 40 players or less because it shared hardware with the campus USENET server.  If we let more than 40 people on, it used too much RAM *AND* would start missing ticks (DikuMUD processed everything in a loop, run once every 250ms… it it takes longer than that, you miss a tick).

Sent from Mail for Windows 10

**Comment by thefallentree** [comment] 2017-09-25 20:21
Lets focus on the specific issue and move offtopic discussion to the forum if needed.

**Comment by cartercheng** [comment] 2017-09-26 16:11
Quix i think you basically made the same point twice. :-)

**Comment by cartercheng** [comment] 2017-10-04 07:54
Maybe can use the tencent rapidjson for this but it converts to a builtin document format rather than having hooks that can be used to do a customizable read/write

**Comment by thefallentree** [comment] 2019-01-30 22:49
dupe with #427

**Closed by thefallentree** 2019-01-30 22:49 UTC
