### ISSUE TITLE
Driver crash - Segfault

### ISSUE THREAD

**Issue by gesslar** [fluffos/fluffos#678] opened 2020-10-21 04:56 UTC
```
/frogdice/thresh_fluffos/fluffos/src/vm/internal/base/svalue.cc:37:7: runtime error: member access within misaligned address 0xffffffffffffffcc for type 'struct malloc_block_t', which requires 8 byte alignment
0xffffffffffffffcc: note: pointer points here
<memory cannot be printed>

Program received signal SIGSEGV, Segmentation fault.
0x000055555692be7c in assign_svalue_no_free (to=0x555557c7b510 <_ZL6_stack.lto_priv.0+208>,
    from=0x555557c7b4f0 <_ZL6_stack.lto_priv.0+176>)
    at /frogdice/thresh_fluffos/fluffos/src/vm/internal/base/svalue.cc:37
37            INC_COUNTED_REF(to->u.string);
(gdb) b
Breakpoint 1 at 0x55555692be7c: file /frogdice/thresh_fluffos/fluffos/src/vm/internal/base/svalue.cc, line 37.
(gdb) bt
#0  0x000055555692be7c in assign_svalue_no_free (to=0x555557c7b510 <_ZL6_stack.lto_priv.0+208>,
    from=0x555557c7b4f0 <_ZL6_stack.lto_priv.0+176>)
    at /frogdice/thresh_fluffos/fluffos/src/vm/internal/base/svalue.cc:37
#1  0x0000555556a0c90e in eval_instruction (p=<optimized out>)
    at /frogdice/thresh_fluffos/fluffos/src/vm/internal/base/interpret.cc:2271
#2  0x0000555556963ef1 in apply_low (fun=<optimized out>, ob=0x6110011fc780, num_arg=<optimized out>)
    at /frogdice/thresh_fluffos/fluffos/src/vm/internal/apply.cc:270
#3  0x000055555696dda3 in apply (where=<optimized out>, num_arg=1, ob=<optimized out>, fun=<optimized out>)
    at /frogdice/thresh_fluffos/fluffos/src/vm/internal/apply.cc:296
#4  safe_apply (fun=<optimized out>, ob=<optimized out>, num_arg=1, where=<optimized out>)
    at /frogdice/thresh_fluffos/fluffos/src/vm/internal/apply.cc:325
#5  0x0000555556570b97 in call_callback (fd=<optimized out>, what=<optimized out>, num_arg=<optimized out>)
    at /usr/include/c++/9/bits/stl_deque.h:273
#6  0x00005555565ca6c9 in socket_write_select_handler (fd=2)
    at /frogdice/thresh_fluffos/fluffos/src/packages/sockets/socket_efuns.cc:1259
#7  (anonymous namespace)::on_lpc_sock_write (fd=<optimized out>, what=<optimized out>, arg=<optimized out>)
    at /frogdice/thresh_fluffos/fluffos/src/packages/sockets/socket_efuns.cc:47
#8  0x00007ffff5db7fde in ?? () from /lib/x86_64-linux-gnu/libevent-2.1.so.7
#9  0x00007ffff5db887f in event_base_loop () from /lib/x86_64-linux-gnu/libevent-2.1.so.7
#10 0x0000555556c3a2c6 in backend (base=0x617000000080) at /frogdice/thresh_fluffos/fluffos/src/backend.cc:225
#11 driver_main (argc=<optimized out>, argv=<optimized out>) at /frogdice/thresh_fluffos/fluffos/src/mainlib.cc:412
#12 0x00005555562d181d in main (argc=<optimized out>, argv=<optimized out>)
    at /frogdice/thresh_fluffos/fluffos/src/main.cc:5
(gdb) info locals
No locals.
(gdb)`
```

**Comment by gesslar** [comment] 2020-10-21 04:57
I have left gdb open and have not quit, if you need anything else from it.

**Comment by thefallentree** [comment] 2020-10-21 16:33
Looks like Another memory corruption issue, can you reproduce this using
sanitizer build?

**Comment by gesslar** [comment] 2020-10-21 17:12
I did compile the driver with `cmake .. -DPACKAGE_MUDLIB_STATS=OFF -DPACKAGE_DB=1 -DPACKAGE_DB_MYSQL=1 -DPACKAGE_EXTERNAL=ON -DENABLE_SANITIZER=ON`

**Comment by thefallentree** [comment] 2020-10-28 17:46
can't reproduce , closing for now.

**Closed by thefallentree** 2020-10-28 17:46 UTC
