### ISSUE TITLE
LPC Floats 0.0 evaluate to true

### ISSUE THREAD

**Issue by staun** [fluffos/fluffos#632] opened 2020-04-19 18:09 UTC
```
0.0 ? "foo" : "bar" -> "foo"
```

Really?? That seems highly unreasonable. :-)

Perhaps this should be a general issue, and not LIMA, not sure?

**Comment by staun** [comment] 2020-04-19 19:25
Don't have access to one. Could we make a stack of improvements to FluffOS somewhere? I think evaluting 0.0 float to false should be on that list.

**Comment by thefallentree** [comment] 2020-04-19 19:34
I think this is actually an bug in the LPC lexer , which qualify as an bug that should be fixed. let me test this a bit before fixing it. 

In the mean time,  you could always do.  `value >= MIN_FLOAT ? "true" : "false" `

**Comment by seikichin** [comment] 2020-04-19 23:20
I test it on ldmud the result is the same as fluffos except one 0.0=0? "a":"b" return "a" in ldmud

**Comment by seikichin** [comment] 2020-04-20 01:52
Never do equality comparison on floating point numbers; floating point 
is not an exact representation. It is also not unambiguous (i.e. there 
is more than one way to store the same number; but == only compares the 
bit patterns, so it may fail). This is independent of the programming 
language, it's an inherent property of floats. 

If you need to compare a float x to a specific value, you have to use 
something like: 

(abs(x-value) < 0.0001) ? "foo" : "bar"; 

i.e. check if x is within a small environment around the value.

**Comment by staun** [comment] 2020-04-20 05:58
I would argue that the logical test to @thefallentree 's "test suite" above would be
B B B A B. That's what I would expect from any sane driver.

1. 0.0 is false by definition (B)
2. 0 is false by definition (B)
3. 0.0 is the same value as 0 so not greater than (B)
4. 0.0 == 0, so out first (A)
5. As per 4, so 0 < 0.0 is false (B)
6. ALSO: 0.0>=0 is TRUE (A) which is weird when FluffOS thinks 0.0==0 is false and 0.0>0 is false. How the ... does 0.0>=0 then become true? :-D 

So, happy too see @seikichin that 0.0==0 in ldmud :-)

We also need to talk about if we fixed this, would it break code? I would argue no, here's why. We're changing the behaviour of evaluating a float as a boolean:

Old behaviour: 
```
if ( <float> == true )  { ... } //Always true before, nomatter what
```

So essentially that would be the same as:
```
if (1) { ... } //Always true
```

If any MUDs have this construction they could break code, but it's very easily fixed. We could drop a warning or something when it happens? Most like MUDs did this in stead:

```
if (to_int(<float>)==<int>) { ... }
```
Which is just a horrible construction that points to that something is going on at a lower level that is not obvious to the average LPC programmer.

**Comment by thefallentree** [comment] 2020-04-20 06:00
I think the problem is in the LPC lexer, it is okay for an calculated float
value to be not equal 0 ,  but just writing 0.0 should generate an true 0
value.

Which is the real and valid issue here.

**Comment by staun** [comment] 2020-04-20 06:02
Yeah, but we need to argue the point that we're not breaking any MUDs if we want to fix this.

**Comment by thefallentree** [comment] 2020-04-20 06:10
If the bug is indeed in the lexer, we will only be breaking people who
write

if (0.0) {} or

if (0.0 == 0) { }

which I would say almost no one is expecting them to work as it is.

**Comment by staun** [comment] 2020-04-20 07:57
Sure, but  <any float> * 0 == true, right? I don't think lexer will fix that. For me it's about the truth evaluation of floats as well.

**Comment by thefallentree** [comment] 2020-04-21 07:30
This has been fixed in https://github.com/fluffos/fluffos/pull/630/commits/67a80487d71d896398bb775eb874dcac85e0c0e7

This bug was not in the lexer, but rather because inconsistency in the lpc parser.  

Basically  if(X) and if(X == 0) uses two different set of logic to compare stuff,  in if(X) , only int value 0 is being treated as false,   and float 0.0 is not.  this is an clear inconsistency between LPC and C language . 

as demonstrate here
![image](https://user-images.githubusercontent.com/1256464/79837963-268f0a00-8367-11ea-8a55-086b274f8969.png)

**Closed** 2020-05-01 16:04 UTC
Labels: bug
